In [1]:
import numpy as np

In [22]:
a1 = np.array([
    [800, 7890, 56],
    [195, 56, 9463],
    [67, 98, 123432]
])

In [6]:
v0 = np.array([1/3, 1/3, 1/3])

a = np.array([
    [0.7, 0.1, 0.3],
    [0.1, 0.6, 0.2],
    [0.2, 0.3, 0.5]
])

n = [1, 10, 100, 1000, 10000, 100000]

In [20]:
def calculate_cars(n, v, a):
    remaining_cars = []

    for i in n:
        cars_n = np.linalg.matrix_power(a, i)
        remaining_cars.append(np.matmul(cars_n, v))

    return remaining_cars

In [24]:
calculate_cars(n, v=v0, a=a)

[array([0.36666667, 0.3       , 0.33333333]),
 array([0.4115748 , 0.26484018, 0.32358502]),
 array([0.41176471, 0.26470588, 0.32352941]),
 array([0.41176471, 0.26470588, 0.32352941]),
 array([0.41176471, 0.26470588, 0.32352941]),
 array([0.41176471, 0.26470588, 0.32352941])]